[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
hook_source = 'source ~/.config/hooks/denops-popup-preview.lua'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/pum.vim'
hook_source = 'source ~/.config/hooks/pum.lua'
on_source = ['ddc.vim']

[[plugins]]
repo = 'windwp/nvim-autopairs'
hook_source = 'source ~/.config/hooks/autopairs.lua'
on_event = 'InsertEnter'
