[[plugins]]
repo = 'EdenEast/nightfox.nvim'
rev = 'v3.10.0'
hooks_file = '$HOOKS_DIR/nightfox.lua'

[[plugins]]
repo = 'github/copilot.vim'
rev = 'v1.41.0'
hooks_file = '$HOOKS_DIR/copilot.lua'

[[plugins]]
repo = 'mhinz/vim-startify'
hooks_file = '$HOOKS_DIR/startify.lua'

[[plugins]]
repo = 'nanozuki/tabby.nvim'
rev = 'v2.7.4'
hooks_file = '$HOOKS_DIR/tabby.lua'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
rev = 'v1.2.0'
hooks_file = '$HOOKS_DIR/lspconfig.lua'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hooks_file = '$HOOKS_DIR/lualine.lua'
depends = ['nvim-web-devicons']

[[plugins]]
repo = 'ojroques/nvim-osc52'
hooks_file = '$HOOKS_DIR/osc52.lua'
