[[plugins]]
repo = 'windwp/nvim-autopairs'
hooks_file = '$HOOKS_DIR/autopairs.lua'
on_event = 'InsertEnter'

[[plugins]]
repo = 'Shougo/deol.nvim'
hooks_file = '$HOOKS_DIR/deol.lua'
on_event = 'TermOpen'
