[[plugins]]
repo = 'windwp/nvim-autopairs'
hook_source = 'source ~/.config/hooks/autopairs.lua'
on_event = 'InsertEnter'

[[plugins]]
repo = 'Shougo/deol.nvim'
hook_add = 'source ~/.config/hooks/deol.lua'
on_event = 'TermOpen'
