[[plugins]]
repo = 'windwp/nvim-autopairs'
hooks_file = '$HOOKS_DIR/autopairs.lua'
on_event = 'InsertEnter'

[[plugins]]
repo = 'Shougo/deol.nvim'
hooks_file = '$HOOKS_DIR/deol.lua'
on_event = 'TermOpen'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
rev = 'v0.9.3'
hooks_file = '$HOOKS_DIR/nvim-treesitter.lua'
on_event = 'BufRead'
